// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import { Database } from '@/types/supabase';

/**
 * Environment variables for Supabase configuration
 * In production, these should be set in your hosting environment
 */
const supabaseUrl = import.meta.env.VITE_PUBLIC_SUPABASE_URL ||
                    import.meta.env.VITE_SUPABASE_URL ||
                    import.meta.env.NEXT_PUBLIC_SUPABASE_URL ||
                    'https://pgiivokemegrlevfzezg.supabase.co';

const supabaseAnonKey = import.meta.env.VITE_PUBLIC_SUPABASE_ANON_KEY ||
                        import.meta.env.VITE_SUPABASE_ANON_KEY ||
                        import.meta.env.NEXT_PUBLIC_SUPABASE_ANON_KEY ||
                        'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBnaWl2b2tlbWVncmxldmZ6ZXpnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0MDA4OTYsImV4cCI6MjA2MTk3Njg5Nn0.MBDTfgkKb8m7aNLDM6xRi1zxLyP8hyk2pH90Hd6aZw8';

/**
 * Validate environment variables to prevent silent failures
 */
if (supabaseUrl === 'https://your-project.supabase.co' || supabaseAnonKey === 'your-anon-key') {
  console.warn(
    'Missing Supabase credentials. Please set VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY environment variables.'
  );
} else {
  console.log('Supabase URL and key are configured:');
  console.log('URL:', supabaseUrl);
  console.log('Key available:', !!supabaseAnonKey);
  
  // Remove any trailing slash from the URL
  if (supabaseUrl.endsWith('/')) {
    console.warn('Removing trailing slash from Supabase URL');
  }
}

// Fix URL format if needed
const formattedUrl = supabaseUrl.endsWith('/') 
  ? supabaseUrl.slice(0, -1) 
  : supabaseUrl;

/**
 * Create a fresh Supabase client with minimal configuration
 */
let supabase;

try {
  console.log('Creating fresh Supabase client with URL:', formattedUrl);
  
  // Create client with minimal options for auth
  supabase = createClient<Database>(formattedUrl, supabaseAnonKey, {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
      flowType: 'pkce'
    }
  });
  
  // Test the connection immediately
  console.log('Testing client connection...');
  supabase.auth.getSession().then(({ data, error }) => {
    if (error) {
      console.error('Supabase connection test failed:', error);
    } else {
      console.log('Supabase connection test successful:', data.session ? 'Session exists' : 'No session');
    }
  });
  
  console.log('Supabase client created successfully');
} catch (error) {
  console.error('Error creating Supabase client:', error);
  // Provide a fallback client to prevent app crashes
  supabase = createClient('https://your-project.supabase.co', 'your-anon-key');
}

export { supabase };

/**
 * Helper function to get user data safely
 */
export const getCurrentUser = async () => {
  try {
    console.log('Fetching current user session...');
    const { data: { session }, error } = await supabase.auth.getSession();
    
    if (error) {
      console.error('Error in getSession:', error);
      throw error;
    }
    
    if (!session) {
      console.log('No active session found');
      return null;
    }
    
    console.log('Session found, user is authenticated');
    return session.user;
  } catch (error) {
    console.error('Error getting current user:', error);
    return null;
  }
};

/**
 * Get user profile data with caching
 */
export const getUserProfile = async (userId: string) => {
  try {
    console.log('Fetching user profile for ID:', userId);
    const { data, error } = await supabase
      .from('profiles')
      .select('*')
      .eq('user_id', userId)
      .single();
      
    if (error) {
      console.error('Error fetching profile:', error);
      throw error;
    }
    
    console.log('Profile fetched successfully');
    return data;
  } catch (error) {
    console.error('Error getting user profile:', error);
    return null;
  }
};

/**
 * Test function to verify Supabase connection
 */
export const testConnection = async () => {
  try {
    console.log('Testing Supabase connection...');
    const { data, error } = await supabase
      .from('profiles')
      .select('count')
      .limit(1);
      
    if (error) {
      console.error('Connection test failed:', error.message);
      return false;
    }
    
    console.log('Supabase connection successful!', data);
    return true;
  } catch (error) {
    console.error('Connection test failed:', error);
    return false;
  }
};